import type { Metadata } from 'next';
import { cookies } from 'next/headers';
import '../globals.css';
import { ChakraProviderClient } from './ChakraProviderClient';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const initialColorMode = cookies().get('chakra-ui-color-mode')?.value;

  return (
    <html lang='en'>
      <body>
        <ChakraProviderClient
          initialColorMode={initialColorMode as 'light' | 'dark' | undefined}
        >
          {children}
        </ChakraProviderClient>
      </body>
    </html>
  );
}
