import type { Metadata } from 'next';
import '../globals.css';
import { ChakraProviderClient } from './ChakraProviderClient';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <ChakraProviderClient>{children}</ChakraProviderClient>
      </body>
    </html>
  );
}
